### PR TITLE
added a heading with transitions

### PR DESCRIPTION
**Pull request by palakg01**
###### index.html
Created h1 element
###### main.css
Editted a few colors
Added some transition features
###### main.js
Created a JS folder with main.js
Added a typing effect to h1 using javascript

### CODE REVIEW

**Review by tejasmorkar — CHANGES_REQUESTED** [review]
Everything looks good.
@rohitjoshi6 has removed the main.css file from css folder. Could you first pull the changes and merge the 2 main.css files into 1 inside the css folder?

**Comment by rohitjoshi6** [comment]
> Everything looks good.
> @rohitjoshi6 has removed the main.css file from css folder. Could you first pull the changes and merge the 2 main.css files into 1 inside the css folder?

Apologies for the mistake. Should i make a css folder and then make new pull request?

**Comment by tejasmorkar** [comment]
That's fine @rohitjoshi6 
You can add that file in css folder if you want to...

**Comment by tejasmorkar** [comment]
The changes are done

**Pull request merged**
